In [11]:
import pandas as pd

In [12]:
results = pd.read_parquet("/share/pierson/matt/UAIR/outputs/classify_eu_ai_act/classify_eu_ai_act_results.parquet")

In [13]:
results

,article_id,article_path,article_text,core_tuple_verified,country,eu_valid_input_count,keyword_match_count,matched_keywords,relevant_keyword,too_vague_to_process,...,eu_ai_desc,eu_ai_label,eu_ai_relevant_text,eu_ai_reason,eu_ai_raw_json,classification_mode,latency_s,token_usage_prompt,token_usage_output,token_usage_total
0,03dfda7798e486e05faf6085a4805a677bcb1a29,/share/pierson/matt/UAIR/data/us/2023/https:\\...,On a top floor of Kyiv's Cabinet of Ministers ...,True,us,6,89,"[""advisor"", ""ai"", ""algorithm"", ""app"", ""automat...",True,False,...,The urban AI usage intended to be used for pri...,High Risk,AI systems intended to be used as safety compo...,High Risk due to its use in critical infrastru...,"{""Classification"": ""High Risk"", ""Description"":...",eu_ai_act,102.703015,NaN,NaN,NaN
1,31e514346592d8e416f1b939045e803139ccedbc,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,Job seekers around the world agree on one thin...,True,us,6,41,"[""amazon"", ""app"", ""city"", ""cutting-edge"", ""dat...",True,False,...,The urban AI usage intended to be used for mat...,High Risk,"Annex III, Section 4: Employment, workers mana...",High Risk due to use in employment recruitment...,"{""Classification"": ""High Risk"", ""Description"":...",eu_ai_act,102.652118,NaN,NaN,NaN
2,6504df889b8351b37e90f75f3c432232d9faf47e,/share/pierson/matt/UAIR/data/us/2020/https:\\...,"Sundar Pichai, the CEO of Alphabet and its Goo...",True,us,7,26,"[""artificial intelligence"", ""automatic"", ""data...",True,False,...,The urban AI usage intended to be used for imp...,High Risk,"Annex III, point 1: 'Biometrics, insofar as th...",High Risk due to use in healthcare for disease...,"{""Classification"": ""High Risk"", ""Description"":...",eu_ai_act,102.604176,NaN,NaN,NaN
3,d1733e6ed50cd8d56345ba1ea8d6a337c6076784,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Volkswagen refused to track down mom's stolen ...,True,us,7,15,"[""automatic"", ""device"", ""enforcement"", ""facebo...",True,False,...,The urban AI usage intended to be used for loc...,Limited or Low Risk,The EU AI Act applies only to AI systems place...,Limited or Low Risk due to the use being non-E...,"{""Classification"": ""Limited or Low Risk"", ""Des...",eu_ai_act,102.555894,NaN,NaN,NaN
4,d5b39ece389a4190a7b2bb6789e672023c4476a7,/share/pierson/matt/UAIR/data/us/2020/https:\\...,This is a paid press release. Contact the pres...,True,us,7,95,"[""accountable"", ""advisor"", ""algorithm"", ""app"",...",True,False,...,The urban AI usage intended to be used for pro...,Limited or Low Risk,Article 6(2a)(a)-(d): AI systems performing na...,Limited or Low Risk due to its narrow procedur...,"{""Classification"": ""Limited or Low Risk"", ""Des...",eu_ai_act,102.507209,NaN,NaN,NaN
5,7a71c743bb57e5293b51927a59e735cdde68cd15,/share/pierson/matt/UAIR/data/us/2022/https:\\...,Your effort and contribution in providing this...,True,us,4,87,"[""accountability"", ""app"", ""attack"", ""bot"", ""ci...",True,True,...,None,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN
6,913cfa80cfd376b9e1d6f61b32f00ba2e500150c,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Your effort and contribution in providing this...,True,us,3,107,"[""accountability"", ""analysis"", ""app"", ""attack""...",True,True,...,None,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN
7,e55e44ce791c53e9ef848919354a6b6cd3484ccc,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Your effort and contribution in providing this...,True,us,4,66,"[""advanced"", ""analysis"", ""app"", ""bot"", ""city"",...",True,True,...,None,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN

In [14]:
rb_results = pd.read_parquet("/share/pierson/matt/UAIR/outputs/classify_risks_and_benefits/classify_risks_and_benefits_results.parquet")

In [19]:
rb_results

,article_id,article_path,article_text,core_tuple_verified,country,eu_valid_input_count,keyword_match_count,matched_keywords,relevant_keyword,too_vague_to_process,year,rb_desc,rb_human_rights,rb_sdgs,rb_additional,classification_mode,latency_s,token_usage_prompt,token_usage_output,token_usage_total
0,03dfda7798e486e05faf6085a4805a677bcb1a29,/share/pierson/matt/UAIR/data/us/2023/https:\\...,On a top floor of Kyiv's Cabinet of Ministers ...,True,us,6,89,"[""advisor"", ""ai"", ""algorithm"", ""app"", ""automat...",True,False,2023,The AI system is intended to be used for prior...,"{""Negative Impacts"": [{""Article 3"": ""Negative""...","{""Negative Impacts"": [{""SDG 1"": ""Negative"", ""B...","{""Negative Impacts"": [{""Economic Impacts"": ""Un...",risks_and_benefits,565.114340,NaN,NaN,NaN
1,31e514346592d8e416f1b939045e803139ccedbc,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,Job seekers around the world agree on one thin...,True,us,6,41,"[""amazon"", ""app"", ""city"", ""cutting-edge"", ""dat...",True,False,2017,The AI system is designed to analyze resume da...,"{""Negative Impacts"": [{""Article 1"": ""Negative""...","{""Negative Impacts"": [{""SDG 1"": ""Negative"", ""R...","{""Negative Impacts"": [{""Economic Impacts"": ""Un...",risks_and_benefits,564.993053,NaN,NaN,NaN
2,6504df889b8351b37e90f75f3c432232d9faf47e,/share/pierson/matt/UAIR/data/us/2020/https:\\...,"Sundar Pichai, the CEO of Alphabet and its Goo...",True,us,7,26,"[""artificial intelligence"", ""automatic"", ""data...",True,False,2020,The AI system is designed to analyze medical i...,"{""Negative Impacts"": [{""Article 12"": ""Negative...","{""Negative Impacts"": [{""SDG 10"": ""Negative"", ""...","{""Negative Impacts"": [{""Economic Impacts"": ""Un...",risks_and_benefits,564.867966,NaN,NaN,NaN
3,d1733e6ed50cd8d56345ba1ea8d6a337c6076784,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Volkswagen refused to track down mom's stolen ...,True,us,7,15,"[""automatic"", ""device"", ""enforcement"", ""facebo...",True,False,2023,The AI system is designed to locate stolen veh...,"{""Negative Impacts"": [{""Article 12"": ""Negative...","{""Negative Impacts"": [{""SDG 10"": ""Negative"", ""...","{""Negative Impacts"": [{""Economic Impacts"": ""Un...",risks_and_benefits,564.743720,NaN,NaN,NaN
4,d5b39ece389a4190a7b2bb6789e672023c4476a7,/share/pierson/matt/UAIR/data/us/2020/https:\\...,This is a paid press release. Contact the pres...,True,us,7,95,"[""accountable"", ""advisor"", ""algorithm"", ""app"",...",True,False,2020,The AI system is designed to provide clinical ...,"{""Negative Impacts"": [{""Article 1"": ""Negative""...","{""Negative Impacts"": [{""SDG 1"": ""Negative"", ""B...","{""Negative Impacts"": [{""Economic Impacts"": ""Un...",risks_and_benefits,564.615697,NaN,NaN,NaN
5,7a71c743bb57e5293b51927a59e735cdde68cd15,/share/pierson/matt/UAIR/data/us/2022/https:\\...,Your effort and contribution in providing this...,True,us,4,87,"[""accountability"", ""app"", ""attack"", ""bot"", ""ci...",True,True,2022,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN
6,913cfa80cfd376b9e1d6f61b32f00ba2e500150c,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Your effort and contribution in providing this...,True,us,3,107,"[""accountability"", ""analysis"", ""app"", ""attack""...",True,True,2023,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN
7,e55e44ce791c53e9ef848919354a6b6cd3484ccc,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Your effort and contribution in providing this...,True,us,4,66,"[""advanced"", ""analysis"", ""app"", ""bot"", ""city"",...",True,True,2021,None,None,None,None,too_vague_to_process,NaN,NaN,NaN,NaN

In [20]:
rb_results.iloc[0]['rb_desc']

'The AI system is intended to be used for prioritizing demining efforts in post-conflict zones by analyzing satellite imagery and sensor data to detect potential mine presence. It enables data-driven decision-making to guide humanitarian demining operations, aiming to accelerate the safe return of civilians to affected areas.'

In [21]:
nov6_test_rb = pd.read_parquet("/share/pierson/matt/UAIR/outputs/2025-11-06/19-06-18/full_event_pipeline/outputs/classify_risk_benefits/classify_risk_benefits_results.parquet")

In [24]:
nov6_test_rb['rb_desc'].values

array(['The AI system is designed to automate identity verification and social service delivery through biometric data analysis and predictive risk modeling, enabling faster access to public benefits and services. It integrates real-time environmental, demographic, and behavioral data to optimize resource allocation in health, education, agriculture, and urban planning, aiming to enhance equity and efficiency in public systems.'],
      dtype=object)

In [25]:
nov6_test_decompose = pd.read_parquet("/share/pierson/matt/UAIR/outputs/2025-11-06/19-06-18/full_event_pipeline/outputs/decompose_nbl/tuples.parquet")

In [26]:
nov6_test_decompose

,article_id,article_path,article_text,batch_uuid,classification_mode,country,embeddings,generated_text,generated_tokens,is_relevant,...,identity_of_ai_developer,location_of_ai_deployer,location_of_ai_subject,date_and_time_of_event,deployment_space,list_of_harms_that_occurred,list_of_risks_that_occurred,list_of_benefits_that_occurred,missing,_progress_row
0,28c8ea0d31634356536b54323f32aa1b21844248,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,Skip Navigation\nMarkets\nPre-Markets\nU.S. Ma...,6bbab3c9ae934065b80ddb301c1b9360,llm_relevance,us,None,"{\n ""deployment_domain"": ""Public and privat...","[515, 262, 330, 82213, 20111, 788, 330, 12676,...",True,...,None,United States,United States,2023-04-15 11:30,None,"[""Drivers were tracked without consent due to ...","[""Potential violation of privacy due to unauth...","[""Improved traffic flow analysis and reduced c...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
1,d1d452944801d33e321d4981bcd6a60c81733e93,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,It was supposed to be a routine resupply missi...,6bbab3c9ae934065b80ddb301c1b9360,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defe...","[515, 262, 330, 82213, 20111, 788, 330, 44, 20...",True,...,USC Davis School of Gerontology and Weill Corn...,United States,United States,2013-09-01 00:00,None,"[""Military veterans were psychologically retra...","[""Potential exacerbation of PTSD symptoms in v...","[""Military veterans showed significant reducti...","[""deployment_space"", ""identity_of_ai_deployer""]",1
2,f1379417d761804cc4de55c8f9625ade1b33c470,/share/pierson/matt/UAIR/data/us/2017/https:\\...,Best of the\nBest\nEditors' picks and our top ...,6bbab3c9ae934065b80ddb301c1b9360,llm_relevance,us,None,"{\n ""deployment_domain"": ""Education and voc...","[515, 262, 330, 82213, 20111, 788, 330, 39134,...",True,...,None,Global,Global,2025-07-19 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
3,06ec2f14f9997562c8b47a030f7f3e6fe8d277cd,/share/pierson/matt/UAIR/data/us/2024/https:\\...,OpenAI whistleblower Suchir Balaji dead at age...,6bbab3c9ae934065b80ddb301c1b9360,llm_relevance,us,None,"{\n ""deployment_domain"": ""Arts and Entertai...","[515, 262, 330, 82213, 20111, 788, 330, 9286, ...",True,...,OpenAI,"San Francisco, California, United States",Global,2023-10-01 00:00,None,"[""Suchir Balaji was found dead by suicide due ...","[""Potential psychological harm to researchers ...","[""Increased public awareness about potential c...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
4,b56766865e266d0cd8e60ab42df9c7b2ead50e79,/share/pierson/matt/UAIR/data/us/2024/https:\\...,"Every weekday, the CNBC Investing Club with Ji...",9c8858300e5a4b01be1f62dd5b85c560,llm_relevance,us,None,"{\n ""deployment_domain"": ""Finance and Inves...","[515, 262, 330, 82213, 20111, 788, 330, 78088,...",True,...,CNBC Investing Club,United States,United States,2024-04-18 13:00,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
5,6504df889b8351b37e90f75f3c432232d9faf47e,/share/pierson/matt/UAIR/data/us/2020/https:\\...,"Sundar Pichai, the CEO of Alphabet and its Goo...",9c8858300e5a4b01be1f62dd5b85c560,llm_relevance,us,None,"{\n ""deployment_domain"": ""Health and Health...","[515, 262, 330, 82213, 20111, 788, 330, 14542,...",True,...,None,United States,United States,2020-01-22 00:00,None,[],[],[],"[""deployment_space"", ""identity_of_ai_deployer""...",1
6,638db891c07e353e7ae73aa641618e75b83643be,/share/pierson/matt/UAIR/data/us/2019/https:\\...,Mark Zuckerberg announced on Tuesday that he w...,9c8858300e5a4b01be1f62dd5b85c560,llm_relevance,us,None,"{\n ""deployment_domain"": ""Public and privat...","[515, 262, 330, 82213, 20111, 788, 330, 12676,...",True,...,None,None,None,2019-09-10 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""location_of_ai_de...",1
7,f56281c9f3b63bc9411ca7d861ec50e2da83d132,/share/pierson/matt/UAIR/data/us/2019/https:\\...,"""Terminator: Dark Fate,"" the sixth installment...",9c8858300e5a4b01be1f62dd5b85c560,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defens...","[515, 220, 330, 82213, 20111, 788, 330, 85326,...",True,...,Military technology developers,South Korea,South Korea,None,None,"[""South Korean soldiers were exposed to potent...","[""Potential escalation of armed conflict due t...","[""Enhanced border defense capabilities through...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
8,3e4304e1e18f102a40773e82a662aebb54c59f00,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Microsoft officially put the Cortana app for i...,5a8b23d72af549c0b1dd8e35a6daea50,llm_relevance,us,None,"{\n ""deployment_domain"": ""Health and Health...","[515, 262, 330, 82213, 20111, 788, 330, 14542,...",True,...,Microsoft,United States,Global,2023-04-12 00:00,None,"[""Cortana mobile users were unable to access r...","[""Potential disruption of personal task manage...","[""Seamless integration of reminders and task l...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
9,e8d329893b79ce35c7ce152f79daebc11e8c4063,/share/pierson/matt/UAIR/data/us/2017/https:\\...,Skip Navigation\nMarkets\nPre-Markets\nU.S. Ma...,5a8b23d72af549c0b1dd8e35a6daea50,llm_relevance,us,None,"{\n ""deployment_domain"": ""Urban Planning"",\n ...","[515, 220, 330, 82213, 20111, 788, 330, 93268,...",True,...,None,United States,United States,2023-09-15 08:30,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
10,b0b5d11dc25bac43e1ea7a7891330013ee147481,/share/pierson/matt/UAIR/data/us/2024/https:\\...,"If the reports are true, 2025 could mark a few...",5a8b23d72af549c0b1dd8e35a6daea50,llm_relevance,us,None,"{\n ""deployment_domain"": ""Smart home"",\n ...","[515, 262, 330, 82213, 20111, 788, 330, 33817,...",True,...,Apple,United States,Global,2025-01-01 00:00,None,"[""iPhone users experienced limited functionali...","[""Potential customer dissatisfaction due to Ap...","[""Improved user experience for certain tasks s...","[""deployment_space"", ""date_and_time_of_event""]",1
11,913cfa80cfd376b9e1d6f61b32f00ba2e500150c,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Your effort and contribution in providing this...,5a8b23d72af549c0b1dd8e35a6daea50,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defens...","[515, 220, 330, 82213, 20111, 788, 330, 85326,...",True,...,None,None,None,2023-03-24 00:00,None,"[""Ukrainian civilians were killed in Russian m...","[""Potential escalation of warfare due to susta...","[""Increased transparency of conflict-related a...","[""identity_of_ai_developer"", ""identity_of_ai_d...",1
12,f61b2d6d5bcb7c5e056fed7146775858716b3d45,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Your effort and contribution in providing this...,f5ff7213799c47c09d8b1e95492f638d,llm_relevance,us,None,"{\n ""deployment_domain"": ""Public and private ...","[515, 220, 330, 82213, 20111, 788, 330, 12676,...",True,...,CNN,United States,United States,2021-10-07 15:30,None,"[""Healthcare workers were put at higher risk o...","[""Potential spread of the virus due to decline...","[""Improved protection against severe disease a...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
13,7a71c743bb57e5293b51927a59e735cdde68cd15,/share/pierson/matt/UAIR/data/us/2022/https:\\...,Your effort and contribution in providing this...,f5ff7213799c47c09d8b1e95492f638d,llm_relevance,us,None,"{\n ""deployment_domain"": ""Media and Communi...","[515, 262, 330, 82213, 20111, 788, 330, 12661,...",True,...,CNN,United States,Global,2022-04-16 00:00,None,[],[],[],"[""deployment_space"", ""identity_of_ai_deployer""]",1
14,0ab17dfc70c4f7b931e9b11c4ac32a45fa712202,/share/pierson/matt/UAIR/data/us/2019/https:\\...,UK primary school math question stumps a teach...,f5ff7213799c47c09d8b1e95492f638d,llm_relevance,us,None,"{\n ""deployment_domain"": ""Education and voc...","[515, 262, 330, 82213, 20111, 788, 330, 39134,...",True,...,None,None,None,None,None,[],[],[],"[""deployment_domain"", ""deployment_purpose"", ""d...",1
15,e4ffb64f21330bd983d68fa3d6a88b9f35e852b4,/share/pierson/matt/UAIR/data/us/2024/https:\\...,LA City Council seeks improved safety for Metr...,f5ff7213799c47c09d8b1e95492f638d,llm_relevance,us,None,"{\n ""deployment_domain"": ""Public and privat...","[515, 262, 330, 82213, 20111, 788, 330, 12676,...",True,...,None,None,None,2024-04-01 00:00,None,"[""Two Metro bus drivers were attacked, one of ...","[""Potential escalation of violence against tra...","[""Installation of plexiglass barriers on appro...","[""identity_of_ai_developer"", ""location_of_ai_d...",1
16,bfc31981ee054c953f30eb01f1ba9a9f991ad9fa,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Your effort and contribution in providing this...,3e664d15e94e4e73af9081d31af0b44b,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defens...","[515, 220, 330, 82213, 20111, 788, 330, 85326,...",True,...,None,None,None,2023-08-08 20:00,None,"[""Rescuers and civilians were killed and injur...","[""Potential endangerment of civilians and emer...","[""Improved military coordination and strategic...","[""identity_of_ai_deployer"", ""location_of_ai_de...",1
17,dc81b66ffbedb21147dac0bef78c75aa4c664be6,/share/pierson/matt/UAIR/data/us/2015/http:\\n...,Hurricane Erin expected to pick up speed as it...,3e664d15e94e4e73af9081d31af0b44b,llm_relevance,us,None,"{\n ""deployment_domain"": null,\n ""purpos...","[515, 262, 330, 82213, 20111, 788, 845, 345, 2...",True,...,None,None,None,None,None,[],[],[],"[""deployment_domain"", ""deployment_purpose"", ""d...",1
18,a9b618f711ef7b5a7ee8a701f8dd03d5e6df2691,/share/pierson/matt/UAIR/data/us/2017/http:\\a...,Carrie Fisher Won't Be Digitally Recreated in ...,3e664d15e94e4e73af9081d31af0b44b,llm_relevance,us,None,"{\n ""deployment_domain"": ""Entrepreneurship""...","[515, 262, 330, 82213, 20111, 788, 330, 2250, ...",True,...,Lucasfilm,United States,United States,2016-12-27 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
19,401f7dff6323cf738d1929e3850849ade26acf46,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,The ancestral home of DeLesslin “Roo” George-W...,3e664d15e94e4e73af9081d31af0b44b,llm_relevance,us,None,"{\n ""deployment_domain"": ""Crisis Management...","[515, 262, 330, 82213, 20111, 788, 330, 34, 59...",True,...,None,None,None,None,None,None,None,None,[],1
20,2b53784a3cd87a07985bbdc026846dafd4c9b213,/share/pierson/matt/UAIR/data/us/2024/https:\\...,Apple's reported product delays keep on coming...,00fea88bea35455f82803cb6e5a2f286,llm_relevance,us,None,"{\n ""deployment_domain"": ""Smart home"",\n ""pu...","[515, 220, 330, 82213, 20111, 788, 330, 33817,...",True,...,None,None,None,2025-06-01 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""location_of_ai_de...",1
21,b43b703fb23a0c51e33930a413591dedf369aaef,/share/pierson/matt/UAIR/data/us/2019/https:\\...,Los Angeles is pumping the brakes on scooter c...,00fea88bea35455f82803cb6e5a2f286,llm_relevance,us,None,"{\n ""deployment_domain"": ""Urban Planning"",\n ...","[515, 220, 330, 82213, 20111, 788, 330, 93268,...",True,...,Remix,"Los Angeles, California","Los Angeles, California",2024-03-21 14:03,None,"[""Scooter users were exposed to privacy risks ...","[""Potential re-identification of individuals f...","[""Improved city planning for micromobility inf...","[""identity_of_ai_deployer"", ""deployment_space""]",1
22,e55e44ce791c53e9ef848919354a6b6cd3484ccc,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Your effort and contribution in providing this...,00fea88bea35455f82803cb6e5a2f286,llm_relevance,us,None,"{\n ""deployment_domain"": ""Media and Communica...","[515, 220, 330, 82213, 20111, 788, 330, 12661,...",True,...,None,None,None,2021-10-14 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""location_of_ai_de...",1
23,506864e79d44b66cb8da727a2510477f8d782bba,/share/pierson/matt/UAIR/data/us/2022/https:\\...,Your effort and contribution in providing this...,00fea88bea35455f82803cb6e5a2f286,llm_relevance,us,None,"{\n ""deployment_domain"": ""Media and Communica...","[515, 220, 330, 82213, 20111, 788, 330, 12661,...",True,...,CNN,United States,Global,2022-04-30 04:00,None,"[""Readers were exposed to biased or incomplete...","[""Potential misinformation due to machine lear...","[""Improved reader engagement through personali...","[""identity_of_ai_deployer"", ""deployment_space""]",1
24,22060d1f4d91902a78cfe5b3c8b596e614fe708f,/share/pierson/matt/UAIR/data/us/2019/https:\\...,HSA hiring investigators to crack down on Kpod...,707d0c59139147399ff65bb8f1e2f821,llm_relevance,us,None,"{\n ""deployment_domain"": ""Law enforcement"",...","[515, 262, 330, 82213, 20111, 788, 330, 38066,...",True,...,null,Singapore,Singapore,2023-08-13 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
25,d1733e6ed50cd8d56345ba1ea8d6a337c6076784,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Volkswagen refused to track down mom's stolen ...,707d0c59139147399ff65bb8f1e2f821,llm_relevance,us,None,"{\n ""deployment_domain"": ""Transport and Log...","[515, 262, 330, 82213, 20111, 788, 330, 27560,...",True,...,Volkswagen,United States,"Illinois, United States",2024-02-23 10:00,None,"[""An infant was left unattended in a stolen ve...","[""Potential endangerment of a child and mother...","[""Recovery of an infant from a stolen vehicle ...","[""identity_of_ai_deployer"", ""deployment_space""]",1
26,d5b39ece389a4190a7b2bb6789e672023c4476a7,/share/pierson/matt/UAIR/data/us/2020/https:\\...,This is a paid press release. Contact the pres...,707d0c59139147399ff65bb8f1e2f821,llm_relevance,us,None,"{\n ""deployment_domain"": ""Health and Healthca...","[515, 220, 330, 82213, 20111, 788, 330, 14542,...",True,...,None,"Duarte, California",United States,2020-10-06 00:00,None,[],[],"[""Improved clinical outcomes and quality of li...","[""identity_of_ai_deployer"", ""identity_of_ai_de...",1
27,032a55b79054cd637d3cf83a18087c9d8c7b03b5,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Sen. Bernie Sanders is the new head of a key S...,707d0c59139147399ff65bb8f1e2f821,llm_relevance,us,None,"{\n ""deployment_domain"": ""Employment, worke...","[515, 262, 330, 82213, 20111, 788, 330, 36032,...",True,...,None,None,None,None,None,[],[],[],"[""date_and_time_of_event"", ""identity_of_ai_dep...",1
28,3ebf86f7d597559fe4dbdb17c36114daaf93fc35,/share/pierson/matt/UAIR/data/us/2020/https:\\...,Skip Navigation\nMarkets\nPre-Markets\nU.S. Ma...,43eca5bd1d764e5f80b2932b12ed17d9,llm_relevance,us,None,"{\n ""deployment_domain"": ""Urban Planning"",\n ...","[515, 220, 330, 82213, 20111, 788, 330, 93268,...",True,...,None,United States,United States,2022-09-15 14:30,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
29,923caf8f843df08680abbd2b7a46c5a4d9fd90e1,/share/pierson/matt/UAIR/data/us/2021/https:\\...,Your effort and contribution in providing this...,43eca5bd1d764e5f80b2932b12ed17d9,llm_relevance,us,None,"{\n ""deployment_domain"": ""Media and Communi...","[515, 262, 330, 82213, 20111, 788, 330, 12661,...",True,...,None,None,None,2021-05-21 00:00,None,[],[],[],"[""deployment_space"", ""identity_of_ai_deployer""...",1
30,dad2ce24d939e62af3987e74e52eba8435ce7103,/share/pierson/matt/UAIR/data/us/2024/https:\\...,The Summary\n- An advanced diagnostic test use...,43eca5bd1d764e5f80b2932b12ed17d9,llm_relevance,us,None,"{\n ""deployment_domain"": ""Health and Health...","[515, 262, 330, 82213, 20111, 788, 330, 14542,...",True,...,None,None,None,2018-01-01 00:00,None,[],[],"[""Improved diagnosis of neurological infection...","[""identity_of_ai_deployer"", ""location_of_ai_de...",1
31,ae8606aa7612e05f8560fb2e77cca0653b3bbff8,/share/pierson/matt/UAIR/data/us/2023/https:\\...,"Fort Worth neighborhood, public safety agencie...",43eca5bd1d764e5f80b2932b12ed17d9,llm_relevance,us,None,"{\n ""deployment_domain"": ""Public and private ...","[515, 220, 330, 82213, 20111, 788, 330, 12676,...",True,...,Surveillance camera system providers,United States,United States,2023-07-04 00:00,None,"[""Residents in Historic Carver Heights, Meadow...","[""Potential fire hazard in residential areas d...","[""Residents in Fort Worth neighborhoods were w...","[""identity_of_ai_deployer"", ""deployment_space""...",1
32,31e514346592d8e416f1b939045e803139ccedbc,/share/pierson/matt/UAIR/data/us/2017/http:\\w...,Job seekers around the world agree on one thin...,44ca262d9d7f43ffbe844c7ad9fa9126,llm_relevance,us,None,"{\n ""deployment_domain"": ""Humanitarian Aid""...","[515, 262, 330, 82213, 20111, 788, 330, 33975,...",True,...,AI for Good Initiative,Global,Global,2018-03-15 14:30,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
33,25e47915b2ece0c7ee3715a5de876e4ce91e54ba,/share/pierson/matt/UAIR/data/us/2022/https:\\...,Your effort and contribution in providing this...,44ca262d9d7f43ffbe844c7ad9fa9126,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defe...","[515, 262, 330, 82213, 20111, 788, 330, 85326,...",True,...,US defense contractors,United States,Ukraine,2022-06-16 00:00,None,"[""American volunteers fighting alongside Ukrai...","[""Potential endangerment of foreign volunteers...","[""Ukraine received increased military aid, inc...","[""deployment_space"", ""identity_of_ai_deployer""]",1
34,27003d9aa587147bf700266107d8a38d2eec86e8,/share/pierson/matt/UAIR/data/us/2023/https:\\...,WASHINGTON — Bombs boom. Tanks trundle. Fighte...,44ca262d9d7f43ffbe844c7ad9fa9126,llm_relevance,us,None,"{\n ""deployment_domain"": ""Military and Defe...","[515, 262, 330, 82213, 20111, 788, 330, 85326,...",True,...,None,None,None,2021-01-01 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""location_of_ai_de...",1
35,56af1fd08b8cf4eca317a6733f5cdff2a52dc5bd,/share/pierson/matt/UAIR/data/us/2015/http:\\w...,Best of the\nBest\nEditors' picks and our top ...,44ca262d9d7f43ffbe844c7ad9fa9126,llm_relevance,us,None,"{\n ""deployment_domain"": ""Smart home""\n ...","[515, 262, 330, 82213, 20111, 788, 330, 33817,...",True,...,None,United States,United States,2025-07-19 00:00,None,[],[],[],"[""identity_of_ai_deployer"", ""identity_of_ai_de...",1
36,7c1f1e0d38ce3bea27801eee3cdb73e7f3698e11,/share/pierson/matt/UAIR/data/us/2020/https:\\...,Your effort and contribution in providing this...,c920dbcc994b4f69bff4e8c6c8942c78,llm_relevance,us,None,"{\n ""deployment_domain"": ""Health and Healthca...","[515, 220, 330, 82213, 20111, 788, 330, 14542,...",True,...,Data and Safety Monitoring Boards (DSMBs),Global,Global,2020-09-10 22:30,None,"[""Students at the University of Alabama were s...","[""Potential spread of the virus among students...","[""Improved surveillance of vaccine safety thro...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
37,e2b96969ed05c1de4e25628543f8335c74678eca,/share/pierson/matt/UAIR/data/us/2017/https:\\...,Best of the\nBest\nEditors' picks and our top ...,c920dbcc994b4f69bff4e8c6c8942c78,llm_relevance,us,None,"{\n ""deployment_domain"": ""Education and voc...","[515, 262, 330, 82213, 20111, 788, 330, 39134,...",True,...,AI productivity tool developers,Global,Global,2025-07-19 00:00,None,[],[],"[""Improved personal time management for studen...","[""identity_of_ai_deployer"", ""identity_of_ai_su...",1
38,b41d704d3b2ca9107872ca1da16cb49b0daa32cc,/share/pierson/matt/UAIR/data/us/2023/https:\\...,Google DeepMind AI reveals potential for thous...,c920dbcc994b4f69bff4e8c6c8942c78,llm_relevance,us,None,"{\n ""deployment_domain"": ""Energy"", \n ""p...","[515, 262, 330, 82213, 20111, 788, 330, 32675,...",True,...,None,United States,Global,2023-06-28 00:00,None,[],[],"[""Improved battery performance due to AI-predi...","[""identity_of_ai_deployer"", ""identity_of_ai_de...",1

In [32]:
nov6_test_verify = pd.read_parquet("/share/pierson/matt/UAIR/outputs/2025-11-06/19-06-18/full_event_pipeline/outputs/verify_nbl/verify_nbl_results.parquet")