In [1]:
import pandas as pd

In [4]:
eu_ai_act_results = pd.read_parquet("/share/pierson/matt/UAIR/outputs/classify_eu_ai_act/oct18_all_classify_eu_ai_act_results.parquet")

In [7]:
eu_ai_act_results.head()

,_progress_row,article_id,article_path,article_text,batch_uuid,chunk_text,classification_mode,country,date___time_of_event,date_and_time_of_event,...,token_usage_prompt,token_usage_total,too_vague_to_process,ts_start,year,eu_ai_desc,eu_ai_label,eu_ai_relevant_text,eu_ai_reason,eu_ai_raw_json
0,1,d13738197fcf6eaa930dd524afb5353250a881c8,/share/ju/matt/sensing-ai-risks/data/global_su...,us port labor talks resume with spotlight on a...,f8a1365cb7ba4e99829c9fa4de137985,us port labor talks resume with spotlight on a...,eu_ai_act,fr,Not known/specified,2024-11-19 02:48,...,None,None,False,1.760816e+09,2025,The urban AI usage intended to be used for inc...,Limited or Low Risk,Article 6(2a)(a) – AI systems intended to perf...,Limited or Low Risk due to performing a narrow...,"{'Classification': 'Limited or Low Risk', 'Des..."
1,1,f6aa47c061540577e97ce9e86935a22b82f53f32,/share/ju/matt/sensing-ai-risks/data/global_su...,new law enables french tax authorities to moni...,f8a1365cb7ba4e99829c9fa4de137985,new law enables french tax authorities to moni...,eu_ai_act,fr,Not known/specified,2024-01-01 00:00,...,None,None,False,1.760816e+09,2025,The urban AI usage intended to be used for mon...,High Risk,"Article 6(2), Annex III, point 5(b): AI system...",High Risk due to use in assessing taxpayer eli...,"{'Classification': 'High Risk', 'Description':..."
2,1,6863134fc143dfeff6fb264461836f33020bf752,/share/ju/matt/sensing-ai-risks/data/global_su...,bank of england policymaker sees risk ai trade...,f8a1365cb7ba4e99829c9fa4de137985,bank of england policymaker sees risk ai trade...,eu_ai_act,fr,Not known/specified,2024-06-18 00:00,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for opt...,Limited or Low Risk,"Article 6(2a), Annex III, point 5(b): AI syste...",Limited or Low Risk due to the AI system being...,"{'Classification': 'Limited or Low Risk', 'Des..."
3,1,666992036a9792803325f4001495f90924b88d9f,/share/ju/matt/sensing-ai-risks/data/global_su...,"apple ai displays fake news headline, prompts ...",f8a1365cb7ba4e99829c9fa4de137985,"apple ai displays fake news headline, prompts ...",eu_ai_act,fr,Not known/specified,2025-01-21 04:27,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for gen...,Limited or Low Risk,Article 6(2a)(a)-(d) – AI systems performing n...,Limited or Low Risk,"{'Classification': 'Limited or Low Risk', 'Des..."
4,1,3f33394ca3947d3aae7a22c623b441520575a310,/share/ju/matt/sensing-ai-risks/data/global_su...,telescope innovations to showcase directinject...,6c457d5004394c908eee2b83c53240f0,telescope innovations to showcase directinject...,eu_ai_act,fr,Not known/specified,2019-06-12 13:00,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for the...,Prohibited,The use of ‘real-time’ remote biometric identi...,Prohibited,"{'Classification': 'Prohibited', 'Description'..."

In [9]:
eu_ai_act_results.eu_ai_label.value_counts()

eu_ai_label
Limited or Low Risk    4003
High Risk               759
Prohibited              339
Name: count, dtype: int64

In [8]:
prohibited = eu_ai_act_results[eu_ai_act_results["eu_ai_label"] == "Prohibited"]
prohibited.head()

,_progress_row,article_id,article_path,article_text,batch_uuid,chunk_text,classification_mode,country,date___time_of_event,date_and_time_of_event,...,token_usage_prompt,token_usage_total,too_vague_to_process,ts_start,year,eu_ai_desc,eu_ai_label,eu_ai_relevant_text,eu_ai_reason,eu_ai_raw_json
4,1,3f33394ca3947d3aae7a22c623b441520575a310,/share/ju/matt/sensing-ai-risks/data/global_su...,telescope innovations to showcase directinject...,6c457d5004394c908eee2b83c53240f0,telescope innovations to showcase directinject...,eu_ai_act,fr,Not known/specified,2019-06-12 13:00,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for the...,Prohibited,The use of ‘real-time’ remote biometric identi...,Prohibited,"{'Classification': 'Prohibited', 'Description'..."
6,1,4f16b7b5f09e8999d5b641d070737f6c6262c4a9,/share/ju/matt/sensing-ai-risks/data/global_su...,nvidia's run:ai deal to get eu antitrust decis...,6c457d5004394c908eee2b83c53240f0,nvidia's run:ai deal to get eu antitrust decis...,eu_ai_act,fr,Not known/specified,2021-08-22 20:15,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for gen...,Prohibited,"The placing on the market, putting into servic...",Prohibited due to deceptive manipulation of pe...,"{'Classification': 'Prohibited', 'Description'..."
42,1,2ea8d8ec7733d987b1ea1a3bcc0e3d4d664b8fb9,/share/ju/matt/sensing-ai-risks/data/global_su...,romania was target of 'aggressive hybrid russi...,8c7b7b0fa3e2408e8d0a391ff21d1132,romania was target of 'aggressive hybrid russi...,eu_ai_act,fr,Not known/specified,2024-11-24 00:00,...,None,None,False,1.760816e+09,2024,The urban AI usage intended to be used for pro...,Prohibited,"Article 5(1)(aa): The placing on the market, p...",Prohibited due to influencing voting behaviour...,"{'Classification': 'Prohibited', 'Description'..."
57,1,6e5e7a9e49bba294c912b513837d6b81a154352c,/share/ju/matt/sensing-ai-risks/data/global_su...,your face is ours : the dangers of facial reco...,8863da4cf24b4156adaf7f9497eaec52,your face is ours : the dangers of facial reco...,eu_ai_act,fr,Not known/specified,2022-12-31 23:59,...,None,None,False,1.760816e+09,2023,The urban AI usage intended to be used for ide...,Prohibited,"Article 5(1)(db): The placing on the market, p...",Prohibited,"{'Classification': 'Prohibited', 'Description'..."
65,1,c0d23c4961580c4f1c3a410ebd2bb85cdbbb915f,/share/ju/matt/sensing-ai-risks/data/global_su...,"biden meets microsoft, google ceos on ai dange...",2c47470e092943378f871d5a18e5b266,"biden meets microsoft, google ceos on ai dange...",eu_ai_act,fr,Not known/specified,2024-05-04 11:45,...,None,None,False,1.760816e+09,2023,The urban AI usage intended to be used for gen...,Prohibited,"Article 5(1)(aa): The placing on the market, p...",Prohibited,"{'Classification': 'Prohibited', 'Description'..."

In [10]:
prohibited.columns

Index(['_progress_row', 'article_id', 'article_path', 'article_text',
       'batch_uuid', 'chunk_text', 'classification_mode', 'country',
       'date___time_of_event', 'date_and_time_of_event',
       'deployment_capability', 'deployment_domain', 'deployment_purpose',
       'deployment_space', 'embeddings', 'eu_valid_input_count',
       'generated_tokens', 'identity_of_ai_deployer',
       'identity_of_ai_developer', 'identity_of_ai_subject', 'is_relevant',
       'keyword_match_count', 'latency_s', 'list_of_benefits_that_occurred',
       'list_of_harms_that_occurred', 'list_of_risks_that_occurred',
       'llm_json', 'llm_output', 'location_of_ai_deployer',
       'location_of_ai_subject', 'matched_keywords', 'metrics', 'missing',
       'num_generated_tokens', 'num_input_tokens', 'params', 'prompt',
       'prompt_token_ids', 'relevance_answer', 'relevant_keyword',
       'request_id', 'time_taken_llm', 'token_usage_output',
       'token_usage_prompt', 'token_usage_total', 'too_vague_to_process',
       'ts_start', 'year', 'eu_ai_desc', 'eu_ai_label', 'eu_ai_relevant_text',
       'eu_ai_reason', 'eu_ai_raw_json'],
      dtype='object')

In [12]:
# subset prohibited to include 'eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event', 'deployment_capability', 'deployment_domain', 'deployment_purpose', 'identity_of_ai_developer', 'identity_of_ai_subject', 'identity_of_ai_deployer', 'location_of_ai_subject', matched_keywords', 'eu_ai_relevant_text', ''list_of_benefits_that_occurred', 'list_of_harms_that_occurred', 'list_of_risks_that_occurred'

prohibited = prohibited[['eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event', 'deployment_capability', 'deployment_domain', 'deployment_purpose', 'identity_of_ai_developer', 'identity_of_ai_subject', 'identity_of_ai_deployer', 'location_of_ai_subject', 'matched_keywords', 'eu_ai_relevant_text', 'list_of_benefits_that_occurred', 'list_of_harms_that_occurred', 'list_of_risks_that_occurred']]
prohibited.head()
prohibited.columns

Index(['eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event',
       'deployment_capability', 'deployment_domain', 'deployment_purpose',
       'identity_of_ai_developer', 'identity_of_ai_subject',
       'identity_of_ai_deployer', 'location_of_ai_subject', 'matched_keywords',
       'eu_ai_relevant_text', 'list_of_benefits_that_occurred',
       'list_of_harms_that_occurred', 'list_of_risks_that_occurred'],
      dtype='object')

In [14]:
# write prohibited to a csv
import os 
os.makedirs("/share/pierson/matt/UAIR/outputs/cases_for_workshop", exist_ok=True)
prohibited.to_csv("/share/pierson/matt/UAIR/outputs/cases_for_workshop/prohibited.csv", index=False)

In [15]:
# now, repeat for 'high risk' 
high_risk = eu_ai_act_results[eu_ai_act_results["eu_ai_label"] == "High Risk"]
high_risk.head()
high_risk.columns

Index(['_progress_row', 'article_id', 'article_path', 'article_text',
       'batch_uuid', 'chunk_text', 'classification_mode', 'country',
       'date___time_of_event', 'date_and_time_of_event',
       'deployment_capability', 'deployment_domain', 'deployment_purpose',
       'deployment_space', 'embeddings', 'eu_valid_input_count',
       'generated_tokens', 'identity_of_ai_deployer',
       'identity_of_ai_developer', 'identity_of_ai_subject', 'is_relevant',
       'keyword_match_count', 'latency_s', 'list_of_benefits_that_occurred',
       'list_of_harms_that_occurred', 'list_of_risks_that_occurred',
       'llm_json', 'llm_output', 'location_of_ai_deployer',
       'location_of_ai_subject', 'matched_keywords', 'metrics', 'missing',
       'num_generated_tokens', 'num_input_tokens', 'params', 'prompt',
       'prompt_token_ids', 'relevance_answer', 'relevant_keyword',
       'request_id', 'time_taken_llm', 'token_usage_output',
       'token_usage_prompt', 'token_usage_total', 'too_vague_to_process',
       'ts_start', 'year', 'eu_ai_desc', 'eu_ai_label', 'eu_ai_relevant_text',
       'eu_ai_reason', 'eu_ai_raw_json'],
      dtype='object')

In [16]:
high_risk = high_risk[['eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event', 'deployment_capability', 'deployment_domain', 'deployment_purpose', 'identity_of_ai_developer', 'identity_of_ai_subject', 'identity_of_ai_deployer', 'location_of_ai_subject', 'matched_keywords', 'eu_ai_relevant_text', 'list_of_benefits_that_occurred', 'list_of_harms_that_occurred', 'list_of_risks_that_occurred']]
high_risk.head()
high_risk.columns

Index(['eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event',
       'deployment_capability', 'deployment_domain', 'deployment_purpose',
       'identity_of_ai_developer', 'identity_of_ai_subject',
       'identity_of_ai_deployer', 'location_of_ai_subject', 'matched_keywords',
       'eu_ai_relevant_text', 'list_of_benefits_that_occurred',
       'list_of_harms_that_occurred', 'list_of_risks_that_occurred'],
      dtype='object')

In [17]:
high_risk.to_csv("/share/pierson/matt/UAIR/outputs/cases_for_workshop/high_risk.csv", index=False)

In [18]:
# now, repeat for 'limited or low risk' 
limited_or_low_risk = eu_ai_act_results[eu_ai_act_results["eu_ai_label"] == "Limited or Low Risk"]
limited_or_low_risk.head()
limited_or_low_risk.columns

Index(['_progress_row', 'article_id', 'article_path', 'article_text',
       'batch_uuid', 'chunk_text', 'classification_mode', 'country',
       'date___time_of_event', 'date_and_time_of_event',
       'deployment_capability', 'deployment_domain', 'deployment_purpose',
       'deployment_space', 'embeddings', 'eu_valid_input_count',
       'generated_tokens', 'identity_of_ai_deployer',
       'identity_of_ai_developer', 'identity_of_ai_subject', 'is_relevant',
       'keyword_match_count', 'latency_s', 'list_of_benefits_that_occurred',
       'list_of_harms_that_occurred', 'list_of_risks_that_occurred',
       'llm_json', 'llm_output', 'location_of_ai_deployer',
       'location_of_ai_subject', 'matched_keywords', 'metrics', 'missing',
       'num_generated_tokens', 'num_input_tokens', 'params', 'prompt',
       'prompt_token_ids', 'relevance_answer', 'relevant_keyword',
       'request_id', 'time_taken_llm', 'token_usage_output',
       'token_usage_prompt', 'token_usage_total', 'too_vague_to_process',
       'ts_start', 'year', 'eu_ai_desc', 'eu_ai_label', 'eu_ai_relevant_text',
       'eu_ai_reason', 'eu_ai_raw_json'],
      dtype='object')

In [19]:
limited_or_low_risk = limited_or_low_risk[['eu_ai_desc', 'eu_ai_label', 'date_and_time_of_event', 'deployment_capability', 'deployment_domain', 'deployment_purpose', 'identity_of_ai_developer', 'identity_of_ai_subject', 'identity_of_ai_deployer', 'location_of_ai_subject', 'matched_keywords', 'eu_ai_relevant_text', 'list_of_benefits_that_occurred', 'list_of_harms_that_occurred', 'list_of_risks_that_occurred']]

In [20]:
# write to csv
limited_or_low_risk.to_csv("/share/pierson/matt/UAIR/outputs/cases_for_workshop/limited_or_low_risk.csv", index=False)